name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: gofmt
        run: make gofmt

      - name: govet
        run: make govet

      - name: Linting
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck ./...

      - name: govulncheck
        run: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./...

      - name: go mod verify
        run: go mod verify

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
